<a href="https://colab.research.google.com/github/Swathi-212002/AI_ML_Avanthi_Swathi/blob/main/Day_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [9]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [11]:
a[0,1]=9
print(a)

[[1 9 3]
 [4 5 6]]


In [12]:
a[:,2]
print(a)

[[1 9 3]
 [4 5 6]]


In [69]:
a=np.ones((5,5))
a[1:4,-4:-1]=0
a[2,2]=9
print(a)





[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [4]:
a=np.full([5,5],1)
a[2:5,1: :2]=0
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 0 1 0 1]
 [1 0 1 0 1]
 [1 0 1 0 1]]


In [66]:
# pratice questions
import numpy as np

In [5]:
#create a null vector of any array
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
# How to find merory size of array
a=np.array([1,2,3,4,5,6])
a.nbytes


48

In [19]:
#create null vector of size 10 but the fifth value which is one
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [28]:
#create a vector with values ranging from 10 to 49
b=np.random.randint(10,49,size=(20))
b

array([34, 15, 33, 18, 15, 12, 18, 40, 47, 26, 48, 46, 32, 12, 42, 39, 27,
       36, 31, 20])

In [29]:
a=np.arange(10,49)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [38]:
# take a random vector and reverse it
a=np.array([1,2,3,4,5])
z = a[-1:-6:-1]
z


array([5, 4, 3, 2, 1])

In [40]:
# create a 3*3 matrix with values ranging from 0 to 8
b=np.random.randint(0,8, size=(3,3))
b

array([[6, 7, 6],
       [2, 2, 1],
       [7, 6, 4]])

In [48]:
b=np.arange(0,9)
x=b.reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [64]:
# find the indices of non zero elements from[1,2,0,0,4,0]
x=np.array([[[1,2,0,0,4,0]]])
x[1:2:4]

array([], shape=(0, 1, 6), dtype=int64)

In [69]:
# find the indices of non zero elements from[1,2,0,0,4,0]
x=np.array([[[1,2,0,0,4,0]]])
print(x(0,0,0))
print(x(0,1))

TypeError: 'numpy.ndarray' object is not callable

In [71]:
np.identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [82]:
a = np.random.randint(1,101,size=(10,10))
print("max = ",np.max(a))

max =  98
